meta_product_name: "Local.ly"
meta_title: "Local.ly - Because we deserve a better community"
meta_description: "The easiest way to report an issue to local authorities and create awareness in your community"
meta_image: "cover.png"
